#!/bin/sh
DAEMON=/usr/bin/gpio-trigger-test

case "$1" in
    start)
        modprobe gpio-trigger
        start-stop-daemon -S --background --exec $DAEMON
        echo "done."
        ;;
    stop)
        start-stop-daemon -K --exec $DAEMON
        modprobe -r gpio-trigger
        echo "done."
        ;;
    restart)
        $0 stop
        $0 start
        echo "done."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0